
import type { TarotCard } from './types';

export const TAROT_DECK: TarotCard[] = [
  // Major Arcana
  { name: 'The Fool', imageUrl: '/cards/m00.jpg' },
  { name: 'The Magician', imageUrl: '/cards/m01.jpg' },
  { name: 'The High Priestess', imageUrl: '/cards/m02.jpg' },
  { name: 'The Empress', imageUrl: '/cards/m03.jpg' },
  { name: 'The Emperor', imageUrl: '/cards/m04.jpg' },
  { name: 'The Hierophant', imageUrl: '/cards/m05.jpg' },
  { name: 'The Lovers', imageUrl: '/cards/m06.jpg' },
  { name: 'The Chariot', imageUrl: '/cards/m07.jpg' },
  { name: 'Strength', imageUrl: '/cards/m08.jpg' },
  { name: 'The Hermit', imageUrl: '/cards/m09.jpg' },
  { name: 'Wheel of Fortune', imageUrl: '/cards/m10.jpg' },
  { name: 'Justice', imageUrl: '/cards/m11.jpg' },
  { name: 'The Hanged Man', imageUrl: '/cards/m12.jpg' },
  { name: 'Death', imageUrl: '/cards/m13.jpg' },
  { name: 'Temperance', imageUrl: '/cards/m14.jpg' },
  { name: 'The Devil', imageUrl: '/cards/m15.jpg' },
  { name: 'The Tower', imageUrl: '/cards/m16.jpg' },
  { name: 'The Star', imageUrl: '/cards/m17.jpg' },
  { name: 'The Moon', imageUrl: '/cards/m18.jpg' },
  { name: 'The Sun', imageUrl: '/cards/m19.jpg' },
  { name: 'Judgement', imageUrl: '/cards/m20.jpg' },
  { name: 'The World', imageUrl: '/cards/m21.jpg' },
  // Wands
  { name: 'Ace of Wands', imageUrl: '/cards/w01.jpg' },
  { name: 'Two of Wands', imageUrl: '/cards/w02.jpg' },
  { name: 'Three of Wands', imageUrl: '/cards/w03.jpg' },
  { name: 'Four of Wands', imageUrl: '/cards/w04.jpg' },
  { name: 'Five of Wands', imageUrl: '/cards/w05.jpg' },
  { name: 'Six of Wands', imageUrl: '/cards/w06.jpg' },
  { name: 'Seven of Wands', imageUrl: '/cards/w07.jpg' },
  { name: 'Eight of Wands', imageUrl: '/cards/w08.jpg' },
  { name: 'Nine of Wands', imageUrl: '/cards/w09.jpg' },
  { name: 'Ten of Wands', imageUrl: '/cards/w10.jpg' },
  { name: 'Page of Wands', imageUrl: '/cards/w11.jpg' },
  { name: 'Knight of Wands', imageUrl: '/cards/w12.jpg' },
  { name: 'Queen of Wands', imageUrl: '/cards/w13.jpg' },
  { name: 'King of Wands', imageUrl: '/cards/w14.jpg' },
  // Cups
  { name: 'Ace of Cups', imageUrl: '/cards/c01.jpg' },
  { name: 'Two of Cups', imageUrl: '/cards/c02.jpg' },
  { name: 'Three of Cups', imageUrl: '/cards/c03.jpg' },
  { name: 'Four of Cups', imageUrl: '/cards/c04.jpg' },
  { name: 'Five of Cups', imageUrl: '/cards/c05.jpg' },
  { name: 'Six of Cups', imageUrl: '/cards/c06.jpg' },
  { name: 'Seven of Cups', imageUrl: '/cards/c07.jpg' },
  { name: 'Eight of Cups', imageUrl: '/cards/c08.jpg' },
  { name: 'Nine of Cups', imageUrl: '/cards/c09.jpg' },
  { name: 'Ten of Cups', imageUrl: '/cards/c10.jpg' },
  { name: 'Page of Cups', imageUrl: '/cards/c11.jpg' },
  { name: 'Knight of Cups', imageUrl: '/cards/c12.jpg' },
  { name: 'Queen of Cups', imageUrl: '/cards/c13.jpg' },
  { name: 'King of Cups', imageUrl: '/cards/c14.jpg' },
  // Swords
  { name: 'Ace of Swords', imageUrl: '/cards/s01.jpg' },
  { name: 'Two of Swords', imageUrl: '/cards/s02.jpg' },
  { name: 'Three of Swords', imageUrl: '/cards/s03.jpg' },
  { name: 'Four of Swords', imageUrl: '/cards/s04.jpg' },
  { name: 'Five of Swords', imageUrl: '/cards/s05.jpg' },
  { name: 'Six of Swords', imageUrl: '/cards/s06.jpg' },
  { name: 'Seven of Swords', imageUrl: '/cards/s07.jpg' },
  { name: 'Eight of Swords', imageUrl: '/cards/s08.jpg' },
  { name: 'Nine of Swords', imageUrl: '/cards/s09.jpg' },
  { name: 'Ten of Swords', imageUrl: '/cards/s10.jpg' },
  { name: 'Page of Swords', imageUrl: '/cards/s11.jpg' },
  { name: 'Knight of Swords', imageUrl: '/cards/s12.jpg' },
  { name: 'Queen of Swords', imageUrl: '/cards/s13.jpg' },
  { name: 'King of Swords', imageUrl: '/cards/s14.jpg' },
  // Pentacles
  { name: 'Ace of Pentacles', imageUrl: '/cards/p01.jpg' },
  { name: 'Two of Pentacles', imageUrl: '/cards/p02.jpg' },
  { name: 'Three of Pentacles', imageUrl: '/cards/p03.jpg' },
  { name: 'Four of Pentacles', imageUrl: '/cards/p04.jpg' },
  { name: 'Five of Pentacles', imageUrl: '/cards/p05.jpg' },
  { name: 'Six of Pentacles', imageUrl: '/cards/p06.jpg' },
  { name: 'Seven of Pentacles', imageUrl: '/cards/p07.jpg' },
  { name: 'Eight of Pentacles', imageUrl: '/cards/p08.jpg' },
  { name: 'Nine of Pentacles', imageUrl: '/cards/p09.jpg' },
  { name: 'Ten of Pentacles', imageUrl: '/cards/p10.jpg' },
  { name: 'Page of Pentacles', imageUrl: '/cards/p11.jpg' },
  { name: 'Knight of Pentacles', imageUrl: '/cards/p12.jpg' },
  { name: 'Queen of Pentacles', imageUrl: '/cards/p13.jpg' },
  { name: 'King of Pentacles', imageUrl: '/cards/p14.jpg' },
];
