
import type { TarotCard } from './types';

export const TAROT_DECK: TarotCard[] = [
  // Major Arcana
  { name: 'The Fool', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/RWS_Tarot_00_Fool.jpg/220px-RWS_Tarot_00_Fool.jpg' },
  { name: 'The Magician', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/RWS_Tarot_01_Magician.jpg/220px-RWS_Tarot_01_Magician.jpg' },
  { name: 'The High Priestess', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/RWS_Tarot_02_High_Priestess.jpg/220px-RWS_Tarot_02_High_Priestess.jpg' },
  { name: 'The Empress', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/RWS_Tarot_03_Empress.jpg/220px-RWS_Tarot_03_Empress.jpg' },
  { name: 'The Emperor', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/RWS_Tarot_04_Emperor.jpg/220px-RWS_Tarot_04_Emperor.jpg' },
  { name: 'The Hierophant', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/RWS_Tarot_05_Hierophant.jpg/220px-RWS_Tarot_05_Hierophant.jpg' },
  { name: 'The Lovers', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/RWS_Tarot_06_Lovers.jpg/220px-RWS_Tarot_06_Lovers.jpg' },
  { name: 'The Chariot', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/RWS_Tarot_07_Chariot.jpg/220px-RWS_Tarot_07_Chariot.jpg' },
  { name: 'Strength', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/RWS_Tarot_08_Strength.jpg/220px-RWS_Tarot_08_Strength.jpg' },
  { name: 'The Hermit', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/RWS_Tarot_09_Hermit.jpg/220px-RWS_Tarot_09_Hermit.jpg' },
  { name: 'Wheel of Fortune', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/RWS_Tarot_10_Wheel_of_Fortune.jpg/220px-RWS_Tarot_10_Wheel_of_Fortune.jpg' },
  { name: 'Justice', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/RWS_Tarot_11_Justice.jpg/220px-RWS_Tarot_11_Justice.jpg' },
  { name: 'The Hanged Man', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/RWS_Tarot_12_Hanged_Man.jpg/220px-RWS_Tarot_12_Hanged_Man.jpg' },
  { name: 'Death', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/RWS_Tarot_13_Death.jpg/220px-RWS_Tarot_13_Death.jpg' },
  { name: 'Temperance', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/RWS_Tarot_14_Temperance.jpg/220px-RWS_Tarot_14_Temperance.jpg' },
  { name: 'The Devil', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/RWS_Tarot_15_Devil.jpg/220px-RWS_Tarot_15_Devil.jpg' },
  { name: 'The Tower', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/RWS_Tarot_16_Tower.jpg/220px-RWS_Tarot_16_Tower.jpg' },
  { name: 'The Star', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/RWS_Tarot_17_Star.jpg/220px-RWS_Tarot_17_Star.jpg' },
  { name: 'The Moon', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/RWS_Tarot_18_Moon.jpg/220px-RWS_Tarot_18_Moon.jpg' },
  { name: 'The Sun', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/RWS_Tarot_19_Sun.jpg/220px-RWS_Tarot_19_Sun.jpg' },
  { name: 'Judgement', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/RWS_Tarot_20_Judgement.jpg/220px-RWS_Tarot_20_Judgement.jpg' },
  { name: 'The World', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/RWS_Tarot_21_World.jpg/220px-RWS_Tarot_21_World.jpg' },
  // Wands
  { name: 'Ace of Wands', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Wands01.jpg/220px-Wands01.jpg' },
  { name: 'Two of Wands', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Wands02.jpg/220px-Wands02.jpg' },
  { name: 'Three of Wands', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Wands03.jpg/220px-Wands03.jpg' },
  { name: 'Four of Wands', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Wands04.jpg/220px-Wands04.jpg' },
  { name: 'Five of Wands', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Wands05.jpg/220px-Wands05.jpg' },
  { name: 'Six of Wands', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Wands06.jpg/220px-Wands06.jpg' },
  { name: 'Seven of Wands', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Wands07.jpg/220px-Wands07.jpg' },
  { name: 'Eight of Wands', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Wands08.jpg/220px-Wands08.jpg' },
  { name: 'Nine of Wands', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Wands09.jpg/220px-Wands09.jpg' },
  { name: 'Ten of Wands', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Wands10.jpg/220px-Wands10.jpg' },
  { name: 'Page of Wands', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Wands11.jpg/220px-Wands11.jpg' },
  { name: 'Knight of Wands', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Wands12.jpg/220px-Wands12.jpg' },
  { name: 'Queen of Wands', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Wands13.jpg/220px-Wands13.jpg' },
  { name: 'King of Wands', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Wands14.jpg/220px-Wands14.jpg' },
  // Cups
  { name: 'Ace of Cups', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Cups01.jpg/220px-Cups01.jpg' },
  { name: 'Two of Cups', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Cups02.jpg/220px-Cups02.jpg' },
  { name: 'Three of Cups', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Cups03.jpg/220px-Cups03.jpg' },
  { name: 'Four of Cups', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Cups04.jpg/220px-Cups04.jpg' },
  { name: 'Five of Cups', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Cups05.jpg/220px-Cups05.jpg' },
  { name: 'Six of Cups', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Cups06.jpg/220px-Cups06.jpg' },
  { name: 'Seven of Cups', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Cups07.jpg/220px-Cups07.jpg' },
  { name: 'Eight of Cups', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Cups08.jpg/220px-Cups08.jpg' },
  { name: 'Nine of Cups', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Cups09.jpg/220px-Cups09.jpg' },
  { name: 'Ten of Cups', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Cups10.jpg/220px-Cups10.jpg' },
  { name: 'Page of Cups', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Cups11.jpg/220px-Cups11.jpg' },
  { name: 'Knight of Cups', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Cups12.jpg/220px-Cups12.jpg' },
  { name: 'Queen of Cups', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Cups13.jpg/220px-Cups13.jpg' },
  { name: 'King of Cups', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Cups14.jpg/220px-Cups14.jpg' },
  // Swords
  { name: 'Ace of Swords', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Swords01.jpg/220px-Swords01.jpg' },
  { name: 'Two of Swords', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Swords02.jpg/220px-Swords02.jpg' },
  { name: 'Three of Swords', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Swords03.jpg/220px-Swords03.jpg' },
  { name: 'Four of Swords', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Swords04.jpg/220px-Swords04.jpg' },
  { name: 'Five of Swords', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Swords05.jpg/220px-Swords05.jpg' },
  { name: 'Six of Swords', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Swords06.jpg/220px-Swords06.jpg' },
  { name: 'Seven of Swords', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Swords07.jpg/220px-Swords07.jpg' },
  { name: 'Eight of Swords', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Swords08.jpg/220px-Swords08.jpg' },
  { name: 'Nine of Swords', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Swords09.jpg/220px-Swords09.jpg' },
  { name: 'Ten of Swords', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Swords10.jpg/220px-Swords10.jpg' },
  { name: 'Page of Swords', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Swords11.jpg/220px-Swords11.jpg' },
  { name: 'Knight of Swords', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Swords12.jpg/220px-Swords12.jpg' },
  { name: 'Queen of Swords', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Swords13.jpg/220px-Swords13.jpg' },
  { name: 'King of Swords', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Swords14.jpg/220px-Swords14.jpg' },
  // Pentacles
  { name: 'Ace of Pentacles', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Pents01.jpg/220px-Pents01.jpg' },
  { name: 'Two of Pentacles', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Pents02.jpg/220px-Pents02.jpg' },
  { name: 'Three of Pentacles', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Pents03.jpg/220px-Pents03.jpg' },
  { name: 'Four of Pentacles', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Pents04.jpg/220px-Pents04.jpg' },
  { name: 'Five of Pentacles', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Pents05.jpg/220px-Pents05.jpg' },
  { name: 'Six of Pentacles', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Pents06.jpg/220px-Pents06.jpg' },
  { name: 'Seven of Pentacles', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Pents07.jpg/220px-Pents07.jpg' },
  { name: 'Eight of Pentacles', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Pents08.jpg/220px-Pents08.jpg' },
  { name: 'Nine of Pentacles', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Pents09.jpg/220px-Pents09.jpg' },
  { name: 'Ten of Pentacles', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Pents10.jpg/220px-Pents10.jpg' },
  { name: 'Page of Pentacles', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Pents11.jpg/220px-Pents11.jpg' },
  { name: 'Knight of Pentacles', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Pents12.jpg/220px-Pents12.jpg' },
  { name: 'Queen of Pentacles', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Pents13.jpg/220px-Pents13.jpg' },
  { name: 'King of Pentacles', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Pents14.jpg/220px-Pents14.jpg' },
];
